# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
Installers:
  - Architecture: x64
    InstallerSha256: 42CACB2AF4588A67CC75451472BD38C497D3EFF75CDFFA7C9BD686C17E2F3836
    InstallerType: zip
    InstallerUrl: https://github.com/Taraflex/voltglean/releases/download/v0.0.2/voltglean-x86_64-pc-windows-msvc.zip
    NestedInstallerFiles:
      - PortableCommandAlias: voltglean
        RelativeFilePath: voltglean.exe
    NestedInstallerType: portable
  - Architecture: x86
    InstallerSha256: 09EE8287C308A82A9C0431E370D50507ADE5CAA3DA3B7277CF880989248A778D
    InstallerType: zip
    InstallerUrl: https://github.com/Taraflex/voltglean/releases/download/v0.0.2/voltglean-i686-pc-windows-msvc.zip
    NestedInstallerFiles:
      - PortableCommandAlias: voltglean
        RelativeFilePath: voltglean.exe
    NestedInstallerType: portable
  - Architecture: arm64
    InstallerSha256: 224A4F617537ED2EEA0613493EC1FEC0ACA8DCDDC0638403D0AAF0F8BE040289
    InstallerType: zip
    InstallerUrl: https://github.com/Taraflex/voltglean/releases/download/v0.0.2/voltglean-aarch64-pc-windows-msvc.zip
    NestedInstallerFiles:
      - PortableCommandAlias: voltglean
        RelativeFilePath: voltglean.exe
    NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.12.0
PackageIdentifier: Taraflex.Voltglean
PackageVersion: 0.0.2
