# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
Author: Taraflex
Documentations:
  - DocumentLabel: Documentation
    DocumentUrl: https://github.com/Taraflex/voltglean
License: MIT OR Apache-2.0
LicenseUrl: https://github.com/Taraflex/voltglean/blob/main/LICENSE-APACHE
ManifestType: defaultLocale
ManifestVersion: 1.12.0
PackageIdentifier: Taraflex.Voltglean
PackageLocale: en-US
PackageName: Voltglean
PackageUrl: https://github.com/Taraflex/voltglean
PackageVersion: 0.0.2
Publisher: Taraflex
PublisherSupportUrl: https://github.com/Taraflex/voltglean/issues
PublisherUrl: https://github.com/Taraflex
ReleaseNotes: '**Full Changelog**: https://github.com/Taraflex/voltglean/compare/v0.0.1...v0.0.2'
ReleaseNotesUrl: https://github.com/Taraflex/voltglean/releases/tag/v0.0.2
ShortDescription: Export Windows power plans as a powershell script
Tags:
  - windows
  - power-management
  - powercfg
  - backup
  - optimization
